### ISSUE TITLE
Cannot create the package

### ISSUE THREAD

**Issue by mwiewior** [prestodb/presto-yarn#26] opened 2015-12-06 14:46 UTC
Hi All - when I'm trying to create the package with maven I get the following exception.
Do you have any idea what's happening?
Marek

Exception:

exception handling                                                                                                                                  [401/9769]
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/home/mwiewiorka/git/presto-yarn/presto-yarn-test/src/test/groovy/com/teradata/presto/yarn/slider/Slider.groovy: 179: The return type of Optional getName() in
 com.teradata.presto.yarn.slider.Slider is incompatible with java.util.Optional getName() in com.teradata.tempto.context.State
. At [179:3]  @ line 179, column 3.
     @Override
     ^

/home/mwiewiorka/git/presto-yarn/presto-yarn-test/src/test/groovy/com/teradata/presto/yarn/utils/NodeSshUtils.groovy: 164: The return type of Optional getName
() in com.teradata.presto.yarn.utils.NodeSshUtils is incompatible with java.util.Optional getName() in com.teradata.tempto.context.State
. At [164:3]  @ line 164, column 3.
     @Override
     ^

2 errors

```
    at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:313)
    at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1235)
    at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:631)
    at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:609)
    at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:586)
    at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyCompilationUnitDeclaration.processToPhase(GroovyCompilationUnitDeclaration.java:184)
    at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyCompilationUnitDeclaration.generateCode(GroovyCompilationUnitDeclaration.java:1632)
    at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:838)
    at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:137)
    at java.lang.Thread.run(Thread.java:745)
```

/home/mwiewiorka/git/presto-yarn/presto-yarn-test/src/test/groovy/com/teradata/presto/yarn/utils/TimeUtils.groovy: 179 Groovy:The return type of Optional getN
ame() in com.teradata.presto.yarn.slider.Slider is incompatible with java.util.Optional getName() in com.teradata.tempto.context.State
/home/mwiewiorka/git/presto-yarn/presto-yarn-test/src/test/groovy/com/teradata/presto/yarn/utils/TimeUtils.groovy: 164 Groovy:The return type of Optional getN
ame() in com.teradata.presto.yarn.utils.NodeSshUtils is incompatible with java.util.Optional getName() in com.teradata.tempto.context.State
exception handling
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:

```
    at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:313)
    at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:1027)
    at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:592)
    at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyCompilationUnitDeclaration.processToPhase(GroovyCompilationUnitDeclaration.java:184)
    at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyCompilationUnitDeclaration.resolve(GroovyCompilationUnitDeclaration.java:2097)
    at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:827)
    at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:137)
    at java.lang.Thread.run(Thread.java:745)
```

exception handling
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:

**Comment by mwiewior** [comment] 2015-12-06 14:51
I found a "dirty" workaround by skipping tests compilation:
mvn clean package -Dmaven.test.skip=true
but I think it would be nice to have all the tests in place.

**Comment by anusudarsan** [comment] 2015-12-06 22:25
I couldnt reproduce the issue. Could you please provide more details of your build environment? Like java version?

**Comment by kokosing** [comment] 2015-12-07 07:01
@mwiewior hey, I have just pushed a change (https://github.com/prestodb/presto-yarn/commit/baf47ef40b05b0af68e52ed3c54ff2f24f49ae7f) which should fix the problem you discovered. As @anusudarsan we were not able to reproduce it, so I am not 100% sure if the fix works.

Although tests are compiled in a default build, tests are not run as they require to have a hadoop cluster (see https://github.com/prestodb/presto-yarn/blob/master/presto-yarn-test/README.md).

**Comment by mwiewior** [comment] 2015-12-07 08:37
Thanks - I will merge/retest and let you know

**Comment by anusudarsan** [comment] 2015-12-10 15:01
@mwiewior Did the fix work for you? If yes, can I close this issue?

**Comment by mwiewior** [comment] 2015-12-10 15:04
@anusudarsan I'm sorry I haven't had time to verify the fix -will let you know asap.

**Comment by anusudarsan** [comment] 2015-12-10 15:04
no rush..was just checking.

**Comment by mwiewior** [comment] 2015-12-10 17:52
Still not able to build the package:

org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/home/mwiewiorka/git/testing/presto-yarn/presto-yarn-test/src/test/groovy/com/teradata/presto/yarn/slider/Slider.groovy: 179: The return type of Optional getN
ame() in com.teradata.presto.yarn.slider.Slider is incompatible with java.util.Optional getName() in com.teradata.tempto.context.State
. At [179:3]  @ line 179, column 3.
     @Override
     ^

/home/mwiewiorka/git/testing/presto-yarn/presto-yarn-test/src/test/groovy/com/teradata/presto/yarn/utils/NodeSshUtils.groovy: 171: The return type of Optional
 getName() in com.teradata.presto.yarn.utils.NodeSshUtils is incompatible with java.util.Optional getName() in com.teradata.tempto.context.State
. At [171:3]  @ line 171, column 3.
     @Override
     ^

2 errors

```
    at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:313)
    at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1235)
    at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:631)
    at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:609)
    at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:586)
    at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyCompilationUnitDeclaration.processToPhase(GroovyCompilationUnitDeclaration.java:184)
    at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyCompilationUnitDeclaration.generateCode(GroovyCompilationUnitDeclaration.java:1632)
    at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:838)
    at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:137)
    at java.lang.Thread.run(Thread.java:745)
```

/home/mwiewiorka/git/testing/presto-yarn/presto-yarn-test/src/test/groovy/com/teradata/presto/yarn/PrestoClusterTest.groovy: 179 Groovy:The return type of Opt
ional getName() in com.teradata.presto.yarn.slider.Slider is incompatible with java.util.Optional getName() in com.teradata.tempto.context.State
/home/mwiewiorka/git/testing/presto-yarn/presto-yarn-test/src/test/groovy/com/teradata/presto/yarn/PrestoClusterTest.groovy: 171 Groovy:The return type of Opt
ional getName() in com.teradata.presto.yarn.utils.NodeSshUtils is incompatible with java.util.Optional getName() in com.teradata.tempto.context.State
exception handling
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:

**Comment by kokosing** [comment] 2015-12-11 06:40
I suspect it has something with groovy compiler issues. What version of groovy do you have? It works just fine with:

```
$ groovyc --version
Groovy compiler version 2.4.4
```

There are several similar issues in groovy reported as this [one](https://issues.apache.org/jira/browse/GROOVY-6713).

**Comment by mwiewior** [comment] 2015-12-11 07:14
I don't have any - I thought that during the compilation would be used  the one you referenced in a pom:
 groovy-eclipse-compiler.version:2.8.0-01

and indeed in the log I can see:
[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files

Should then install external package with a groovy compiler anyway?

**Comment by sopel39** [comment] 2015-12-17 11:22
Hi,

I have run `mvn install` and it worked for my. My configuration is MacOS, Maven 3.3.3, Java 1.8.0_66 and no Groovy installed. What is your configuration?

**Comment by kokosing** [comment] 2016-04-25 10:06
@mwiewior No more groovy is used in presto-yarn, so this issue should no longer exists.

Fixed by https://github.com/prestodb/presto-yarn/commit/8d5a2f12e6ff403818ec1bbc814d5bbf5dc5ae6c

**Closed as completed by kokosing** 2016-04-25 10:06 UTC
